[CmdletBinding()]
param(
    [string]$MigrationName,
    [string]$ProjectRef,
    [switch]$SkipDbPull,
    [switch]$SkipFunctionsDownload,
    [switch]$SyncSecretsTemplate,
    [switch]$WriteLocalEnvFromHost,
    [string]$TemplateOutputPath = "supabase\.env.sync.example",
    [string]$EnvOutputPath = "supabase\.env.local"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Invoke-SupabaseCommand {
    param(
        [string]$Label,
        [string[]]$CommandArgs
    )

    Write-Host ""
    Write-Host "==> $Label" -ForegroundColor Cyan
    Write-Host "supabase $($CommandArgs -join ' ')" -ForegroundColor DarkGray
    & supabase @CommandArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Failed: supabase $($CommandArgs -join ' ')"
    }
}

function Get-SupabaseCommandOutput {
    param(
        [string]$Label,
        [string[]]$CommandArgs
    )

    Write-Host ""
    Write-Host "==> $Label" -ForegroundColor Cyan
    Write-Host "supabase $($CommandArgs -join ' ')" -ForegroundColor DarkGray
    $output = & supabase @CommandArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Failed: supabase $($CommandArgs -join ' ')"
    }
    return $output
}

function Get-EdgeSecretNames {
    param(
        [string[]]$ProjectArgs
    )

    $json = Get-SupabaseCommandOutput -Label "Fetching edge function secret names" -CommandArgs (@("secrets", "list", "--output", "json") + $ProjectArgs)
    if ([string]::IsNullOrWhiteSpace(($json -join ""))) {
        return @()
    }

    $rows = $json | ConvertFrom-Json
    if ($rows -isnot [System.Collections.IEnumerable]) {
        return @()
    }

    return @($rows | ForEach-Object { $_.name } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Sort-Object -Unique)
}

function Get-VaultSecretNamesFromMigrations {
    $files = Get-ChildItem "supabase\migrations\*.sql" -ErrorAction SilentlyContinue
    if ($null -eq $files) {
        return @()
    }

    $names = @()
    $matches = Select-String -Path ($files.FullName) -Pattern "where name = '([^']+)'" -AllMatches
    foreach ($m in $matches) {
        foreach ($capture in $m.Matches) {
            $value = $capture.Groups[1].Value
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                $names += $value
            }
        }
    }

    return @($names | Sort-Object -Unique)
}

function Format-DotenvValue {
    param(
        [AllowNull()]
        [string]$Value
    )

    if ($null -eq $Value) {
        return ""
    }

    $singleLine = $Value -replace "(`r`n|`n|`r)", "\\n"
    if ($singleLine -match "[\s#=]") {
        return '"' + ($singleLine -replace '"', '\"') + '"'
    }

    return $singleLine
}

function Write-DotenvFile {
    param(
        [string]$Path,
        [string[]]$Names,
        [switch]$FromHostEnvironment
    )

    $lines = @(
        "# Generated by scripts/sync-supabase.ps1 on $(Get-Date -Format s)",
        "# Fill values manually if blank."
    )

    $missing = @()
    foreach ($name in $Names) {
        $value = ""
        if ($FromHostEnvironment) {
            $envValue = [Environment]::GetEnvironmentVariable($name)
            if ($null -eq $envValue) {
                $missing += $name
            }
            $value = Format-DotenvValue -Value $envValue
        }
        $lines += "$name=$value"
    }

    $parent = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -Path $parent -ItemType Directory -Force | Out-Null
    }
    Set-Content -Path $Path -Value $lines -Encoding UTF8

    if ($FromHostEnvironment -and $missing.Count -gt 0) {
        Write-Warning "Missing host env vars for $($missing.Count) secret(s): $($missing -join ', ')"
    }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
Set-Location $repoRoot

if (-not (Get-Command supabase -ErrorAction SilentlyContinue)) {
    throw "Supabase CLI is not installed or not on PATH."
}

if (-not (Test-Path "supabase\config.toml")) {
    throw "supabase\config.toml not found. Run this script from a Supabase-initialized repo."
}

$projectArgs = @()
if (-not [string]::IsNullOrWhiteSpace($ProjectRef)) {
    $projectArgs = @("--project-ref", $ProjectRef)
}

if (-not $SkipDbPull) {
    if ([string]::IsNullOrWhiteSpace($MigrationName)) {
        $MigrationName = "{0}_remote_schema" -f (Get-Date -Format "yyyyMMddHHmmss")
    }
    Invoke-SupabaseCommand -Label "Pulling remote database schema" -CommandArgs (@("db", "pull", $MigrationName) + $projectArgs)
}

if (-not $SkipFunctionsDownload) {
    Invoke-SupabaseCommand -Label "Downloading remote edge functions" -CommandArgs (@("functions", "download", "--use-api") + $projectArgs)
}

$latestMigration = Get-ChildItem "supabase\migrations\*.sql" -ErrorAction SilentlyContinue |
    Sort-Object Name |
    Select-Object -Last 1

if ($null -ne $latestMigration) {
    $suspicious = Select-String -Path $latestMigration.FullName -Pattern "\?;" -Quiet
    if ($suspicious) {
        Write-Warning "Potentially malformed SQL detected in $($latestMigration.Name). Review before using for clean rebuilds."
    }
}

if ($SyncSecretsTemplate -or $WriteLocalEnvFromHost) {
    $edgeSecretNames = Get-EdgeSecretNames -ProjectArgs $projectArgs
    $vaultSecretNames = Get-VaultSecretNamesFromMigrations
    $allSecretNames = @($edgeSecretNames + $vaultSecretNames | Sort-Object -Unique)

    if ($allSecretNames.Count -eq 0) {
        Write-Warning "No secret names discovered from edge secrets or migration SQL."
    }

    if ($SyncSecretsTemplate) {
        Write-Host ""
        Write-Host "==> Writing secret template to $TemplateOutputPath" -ForegroundColor Cyan
        Write-DotenvFile -Path $TemplateOutputPath -Names $allSecretNames
    }

    if ($WriteLocalEnvFromHost) {
        Write-Host ""
        Write-Host "==> Writing local env file from host env vars to $EnvOutputPath" -ForegroundColor Cyan
        Write-DotenvFile -Path $EnvOutputPath -Names $allSecretNames -FromHostEnvironment
    }
}

Write-Host ""
Write-Host "Sync complete. Review and commit changes:" -ForegroundColor Green
Write-Host "  git status --short supabase"
